#DEPLOYMENT - NODE API
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: dev-node
  labels:
    app: dev-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-node
  template:
    metadata:
      labels:
        app: dev-node
    spec:
      containers:
      - name: dev-node
        image: #{acr-name-lowercase}#.azurecr.io/#{repository_name}#-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        volumeMounts:
          - name: azure-dev-document-file-share
            mountPath: /mnt/azure-document
      volumes:
        - name: azure-dev-document-file-share
          azureFile:
            shareName: #{file-share-name-doc-dev}#
            secretName: dev-azure-secret
            readOnly: false

---
#SERVICE- NODE API
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-node
  namespace: dev
  name: dev-node-api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: dev-node