#PERSISTENT VOLUM CLAIM
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: azure-storage
      storageAccount: #{storageAccountName}#
---
#PERSISTENT VOLUME
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
  labels: 
    storage: azure-storage
    storageAccount: #{storageAccountName}#
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: mongo-file-share
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl