#PERSISTENT VOLUME
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: kibana
  labels: 
    storage: elasticsearch-azure-storage
    storageAccount: #{storageAccountName}#
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: kibana-azure-secret
    shareName: #{file-share-name-elasticsearch}#
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl