apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certification
  namespace: default
spec:
  dnsNames:
    - node-api.16781f0b56724d758b7a.eastus.aksapp.io
  secretName: certification-app-tls
  issuerRef:
    name: cert-issuer
    kind: Issuer