#PERSISTENT VOLUM CLAIM
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: staging
  name: staging-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: staging-azure-storage
      storageAccount: #{storageAccountName}#
---
#PERSISTENT VOLUME
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: staging
  name: staging-azurefile
  labels: 
    storage: staging-azure-storage
    storageAccount: #{storageAccountName}#
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: staging-azure-secret
    shareName: #{file-share-name}#
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl